// ------- ACCOUNT --------
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const LOGIN_2FACTOR_SUCCESS = 'LOGIN_2FACTOR_SUCCESS'
export const LOGIN_2FACTOR_FAILED = 'LOGIN_2FACTOR_FAILED'

export const LOGOUT = 'LOGOUT'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'

export const REFRESH_SUCCESS = 'REFRESH_SUCCESS'
export const REFRESH_FAILED = 'REFRESH_FAILED'

export const LOAD_ME = 'LOAD_ME'
export const UPDATE_ME = 'UPDATE_ME'

export const LOAD_LOG = 'LOAD_LOG'


export const CONFIRM_EMAIL_SUCCESS = 'CONFIRM_EMAIL_SUCCESS'
export const SEND_PHONE_CODE_SUCCESS = 'SEND_PHONE_CODE_SUCCESS'
export const CONFIRM_PHONE_SUCCESS = 'CONFIRM_PHONE_SUCCESS'
export const ADD_WALLET_ADDRESS_SUCCESS = 'ADD_WALLET_ADDRESS_SUCCESS'
export const UPLOAD_ID = 'UPLOAD_ID'

// ----- PROJECT -----
export const GET_COMPANY = 'GET_COMPANY'
export const LIST_COMPANIES = 'LIST_COMPANIES'
export const LIST_PRESS_RELEASES = 'LIST_PRESS_RELEASES'


// ----- Wallet ----
export const LOAD_WALLET = 'LOAD_WALLET'

export const SYNC_TOKEN_TRANSACTIONS = 'SYNC_TOKEN_TRANSACTIONS'
export const SYNC_ETH_TRANSACTIONS = 'SYNC_ETH_TRANSACTIONS'

export const SYNC_TOKEN_BALANCE = 'SYNC_TOKEN_BALANCE'
export const SYNC_ETH_BALANCE = 'SYNC_ETH_BALANCE'

export const SYNC_ETH_PRICE = 'SYNC_ETH_PRICE'

// ----- Utils ----
export const FOLLOW_UP_STEP = 'FOLLOW_UP_STEP'
